---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
args:
  ETHERPAD_VERSION: "3.1.0"
labels:
  io.hass.type: addon
  org.opencontainers.image.title: Home Assistant Add-on - Etherpad
  org.opencontainers.image.description: Realtime collaborative document editor
  org.opencontainers.image.source: https://github.com/ether/home-assistant-addon-etherpad
  org.opencontainers.image.licenses: Apache-2.0
  org.opencontainers.image.url: https://etherpad.org
  org.opencontainers.image.documentation: https://etherpad.org/doc
  org.opencontainers.image.vendor: Etherpad Foundation
